name: flutter_books
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: any
  rxdart: any
  intl: any
  flutter_datetime_picker: 1.2.5
  build_runner: 1.6.1
  built_value_generator: 6.7.0
  built_value: 6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

